### ISSUE TITLE
Cool. What about using git hooks?

### ISSUE THREAD

**Issue by webflo** [psynaptic/staging#1]
1. Create a bare repository
2. Create _post-receive_ in .git/hooks
3. Add the following code
   <pre>
   CHECKOUT_DIR=/var/www/site_name
   GIT_WORK_TREE=$CHECKOUT_DIR git checkout -f
   /usr/local/bin/drush --root=$CHECKOUT_DIR vset -y staging_last_update `date +%s`
   </pre>
4. chmod +x .git/hooks/post-receive
5. Forget about the cronjob. You do not have to wait 15 minutes after a git push.

**Comment by psynaptic** [comment]
Yeah, great idea. We use these for sending bot messages using bot_commit.module (which is on d.o btw). I'll add these details to the readme.

**Comment by psynaptic** [comment]
Thinking about it, I guess this only works when the dev site is on the same machine as the master repo. Otherwise, we wouldn't be able to run the drush command.

I initially tried to trigger the update command via hook_cron but our repo server controls access using SSH keys so it wasn't straightforward.

**Comment by psynaptic** [comment]
We would authenticate with the repo server I guess, something like:

https://github.com/tizzo/Project-Git-Auth/blob/master/project_git_auth.module

I'm not sure going this route is the best though, post-receive would be ideal if we can make that work with remote servers.
